### ISSUE TITLE
loading error on minecraft

### ISSUE THREAD

**Issue by icycoffee69** [xenia-project/issue-graveyard#437]
every time I click on play game the game gives the following image error, this started after I installed a TU, more specifically tu45, I found it strange because with other updates the game worked perfectly.

How do I solve it?

![WhatsApp Image 2024-02-04 at 03 47 12](https://github.com/xenia-project/issue-graveyard/assets/139078379/06a084ca-2f27-43bc-9d69-3f584da2f921)

**Comment by Margen67** [comment]
Tech support belongs here: https://discord.gg/Q9mxZf9
